version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fb-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc@12345
      POSTGRES_DB: facebook
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fb-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:Abc@12345@db:5432/facebook
      JWT_SECRET: parking-secret-2026
      JWT_EXPIRES_IN: 3600
      BASE_URL: http://171.254.94.233:3002
      CORS_ORIGIN: http://171.254.94.233:8088
      TZ: Asia/Ho_Chi_Minh
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma generate &&
      npm run start
      "
    volumes:
      - .:/app

volumes:
  pgdata:
