version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fb-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc@12345
      POSTGRES_DB: facebook
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fb-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:Abc@12345@db:5432/facebook
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma generate &&
      npm run start
      "
    volumes:
      - .:/app

volumes:
  pgdata:
